# Generated by Django 5.2.6 on 2025-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='status',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
